# This is a basic workflow that extends from the getting-started.yml

name: Artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }}

  make_string:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create a string to be used by subsequent job
        id: step1
        run: echo "hello world" > file.txt
      - name: Upload the string file
        id: step2
        uses: actions/upload-artifact@v3
        with:
            name: file
            path: file.txt

  use_string:
    needs: make_string
    runs-on: self-hosted
    strategy:
      matrix:
        values: [1,2,3,4,5,6,7,8,9,10]
    steps:
        - name: Download the string file
          uses: actions/download-artifact@v3
          with:
            name: file
        - name: Print the final results
          shell: bash
          run: |
            value=`cat file.txt`
            echo "$value ${{ matrix.values }}"