name: Composite

on:
    workflow_dispatch:
    workflow_call:
        # inputs:
        #     config-path:
        #         required: true
        #         type: string
        # secrets:
        #     envPAT:
        #         required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to generate a string
    steps:
      - uses: actions/checkout@v3
      - id: step1
        uses: cfculler/liatrio-bootcamp-composite-actions@v4
        with:
          string-to-print: 'Carson'
      - name: Print string
        run: echo "Final string is ${{ steps.step1.outputs.output1 }}"