name: Composite

on:
    workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to generate a string
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: cfculler/liatrio-bootcamp-composite-actions@v2
        with:
          string-to-print: 'Carson'