name: Diff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      # - name: Cache Go dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      # - name: Generate a token
      #   id: generate_token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #     owner: ${{ github.repository_owner }}

      # - name: Use the token
      #   run: |
      #     git config --global url."https://git:${GH_TOKEN}@github.com".insteadOf https://github.com
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Install tools.go
        run: |
          make install-tools
          for f in bin/*; do
            sudo cp $f /usr/local/bin
          done

      # - name: Localize Manifests (pr)
      #   run: |
      #     task build

      # - name: Check if build branch exists
      #   id: build_branch
      #   run: |
      #     if git show-ref --quiet refs/heads/build; then
      #       echo "exists=yes\n" >> $GITHUB_OUTPUT
      #     else
      #       echo "exists=no\n" >> $GITHUB_OUTPUT
      #     fi

      # - uses: actions/checkout@v4
      #   if: ${{ steps.build_branch.outputs.exists == 'yes' }}
      #   with:
      #     ref: 'build'
      #     path: ".build"

      # - uses: actions/checkout@v4
      #   if: ${{ steps.build_branch.outputs.exists != 'yes' }}
      #   with:
      #     ref: 'main'
      #     path: ".main"

      # - name: Localize Manifests (main)
      #   if: ${{ steps.build_branch.outputs.exists != 'yes' }}
      #   run: |
      #     (cd .main/manifests/; task build)
      #     mv .main/manifests/output .build

      # - uses: int128/diff-action@v1
      #   with:
      #     base: .build
      #     head: manifests/output

      # - uses: actions/labeler@v5

      # TODO: use this
      #
      # - name: Add Reviewers
      #   uses: actions/github-script@v2
      #   with:
      #     script: |
      #       const team = 'ghec_deepa_admin';
      #       const token = process.env.GITHUB_TOKEN;
      #
      #       const response = await github.rest.pulls.addReviewers({
      #         pull_id: context.payload.pull_id,
      #         team_reviewers: [team],
      #         token
      #       });
      #
      #       console.log(response);
