name: Diff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install tools.go
        run: |
          make install-tools
          export PATH=$(pwd)/bin:$PATH

      # - name: Generate a token
      #   id: generate_token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #     owner: ${{ github.repository_owner }}

      # - name: Use the token
      #   run: |
      #     git config --global url."https://git:${GH_TOKEN}@github.com".insteadOf https://github.com
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Localize Manifests (pr)
        run: |
          mkdir -p .localized/
          ./bin/kustomize localize . .localized/pr

      - name: Check if build branch exists
        id: build_branch
        run: |
          if git show-ref --quiet refs/heads/build; then
            echo "exists=yes\n" >> $GITHUB_OUTPUT
          else
            echo "exists=no\n" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        if: ${{ steps.build_branch.outputs.exists == 'yes' }}
        with:
          ref: 'build'
          path: ".localized/main"

      # - name: Localize Manifests (main)
      #   if: ${{ steps.build_branch.outputs.exists != 'yes' }}
      #   run: |
      #     mkdir -p .localized/
      #     ./bin/kustomize localize  ${{ github.server_url }}/${{ github.repository }}.git?ref=main .localized/main

      - uses: int128/diff-action@v1
        with:
          base: .localized/main
          head: .localized/pr
